//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuestas_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENC_TIPOCATALOGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENC_TIPOCATALOGO()
        {
            this.ENC_CATALOGOS = new HashSet<ENC_CATALOGOS>();
            this.ENC_RESPUESTACATALOGO = new HashSet<ENC_RESPUESTACATALOGO>();
        }
    
        public decimal IDTIPOCAT { get; set; }
        public string TIPOCATALOGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENC_CATALOGOS> ENC_CATALOGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENC_RESPUESTACATALOGO> ENC_RESPUESTACATALOGO { get; set; }
    }
}
