//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuestas_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENC_ENCUESTAS_APLICADAS
    {
        public decimal IDENCUESTASAP { get; set; }
        public decimal IDUSUARIO { get; set; }
        public decimal IDENCUESTA { get; set; }
        public string CLAVEENCUESTA { get; set; }
        public System.DateTime FECHACREACION { get; set; }
    
        public virtual ENC_ENCUESTA ENC_ENCUESTA { get; set; }
        public virtual ENC_USUARIOS ENC_USUARIOS { get; set; }
    }
}
