//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuestas_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENC_EMPLEADOS
    {
        public decimal IDEMPLEADO { get; set; }
        public Nullable<decimal> IDUSUARIO { get; set; }
        public string NOMBREEMPLEADO { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual ENC_USUARIOS ENC_USUARIOS { get; set; }
    }
}
