//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuestas_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENC_RESPUESTACATALOGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENC_RESPUESTACATALOGO()
        {
            this.ENC_PREGUNTAS = new HashSet<ENC_PREGUNTAS>();
        }
    
        public decimal IDRESPUESTACATALOGO { get; set; }
        public decimal IDTIPOCAT { get; set; }
        public string RESPUESTANEGATIVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENC_PREGUNTAS> ENC_PREGUNTAS { get; set; }
        public virtual ENC_TIPOCATALOGO ENC_TIPOCATALOGO { get; set; }
    }
}
