//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuestas_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENC_PREGUNTAS
    {
        public decimal IDPREGUNTA { get; set; }
        public string PREGUNTA { get; set; }
        public Nullable<decimal> IDRESPUESTATEXTO { get; set; }
        public Nullable<decimal> IDRESPUESTABOOLEAN { get; set; }
        public Nullable<decimal> IDRESPUESTANUMERO { get; set; }
        public Nullable<decimal> IDRESPUESTACATALOGO { get; set; }
    
        public virtual ENC_RESPUESTABOOLEAN ENC_RESPUESTABOOLEAN { get; set; }
        public virtual ENC_RESPUESTACATALOGO ENC_RESPUESTACATALOGO { get; set; }
        public virtual ENC_RESPUESTANUMERO ENC_RESPUESTANUMERO { get; set; }
        public virtual ENC_RESPUESTATEXTO ENC_RESPUESTATEXTO { get; set; }
    }
}
