//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuestas_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EncAppEntitites : DbContext
    {
        public EncAppEntitites()
            : base("name=EncAppEntitites")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ENC_CATALOGOS> ENC_CATALOGOS { get; set; }
        public virtual DbSet<ENC_EMPLEADOS> ENC_EMPLEADOS { get; set; }
        public virtual DbSet<ENC_ENCUESTA> ENC_ENCUESTA { get; set; }
        public virtual DbSet<ENC_ENCUESTAS_APLICADAS> ENC_ENCUESTAS_APLICADAS { get; set; }
        public virtual DbSet<ENC_PREGUNTAS> ENC_PREGUNTAS { get; set; }
        public virtual DbSet<ENC_RESPUESTABOOLEAN> ENC_RESPUESTABOOLEAN { get; set; }
        public virtual DbSet<ENC_RESPUESTACATALOGO> ENC_RESPUESTACATALOGO { get; set; }
        public virtual DbSet<ENC_RESPUESTANUMERO> ENC_RESPUESTANUMERO { get; set; }
        public virtual DbSet<ENC_RESPUESTATEXTO> ENC_RESPUESTATEXTO { get; set; }
        public virtual DbSet<ENC_ROLES> ENC_ROLES { get; set; }
        public virtual DbSet<ENC_TIPOCATALOGO> ENC_TIPOCATALOGO { get; set; }
        public virtual DbSet<ENC_USUARIOS> ENC_USUARIOS { get; set; }
    }
}
